apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: flask-app-pipeline
spec:
  params:
    - name: imageName
      type: string
    - name: gitSource
      type: string
  tasks:
    - name: build
      taskRef:
        name: build-flask-app
      params:
        - name: imageName
          value: $(params.imageName)
        - name: gitSource
          value: $(params.gitSource)
    - name: deploy
      taskRef:
        name: deploy-flask-app
      params:
        - name: imageName
          value: $(params.imageName)
      runAfter:
        - build