apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-flask-app
spec:
  params:
    - name: imageName
      type: string
  steps:
    - name: deploy
      image: 'quay.io/openshift/origin-cli:latest'
      script: |
        oc new-app $(params.imageName) --allow-missing-imagestream-tags
        oc expose deployment/flask-app --port=5000 --target-port=5000
        oc expose svc/$(params.imageName)